# PARSING AND PROCESSING JSON

import urllib.request
import _json

# USE THE JSON MODULE TO LOAD THE STRING DATA INTO A DICTIONARY
theJSON = json.loads(data)

# NOW WE CAN ACCESS THE CONTENTS OF THE JSON LIKE ANY OTHER PYTHON OBJECT

# OUTPUT THE NUMBER OF EVENTS, PLUS THE MAGNITUDE AND EACH EVENT NAME

# FOR EACH EVENT, PRINT THE PLACE WHERE IT OCCURRED

urlData = ""
